{% set version = "1.3.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-explore
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/explore_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/explore/explore_{{ version }}.tar.gz
  sha256: ff14c1452ce83deee75983f8b35c8050b13e4837b01e1899459926b16d410fdd

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli
    - r-dplyr >=1.1.0
    - r-dt >=0.3.0
    - r-forcats >=1.0.0
    - r-ggplot2 >=3.4.0
    - r-gridextra
    - r-magrittr
    - r-palmerpenguins
    - r-plotly
    - r-rlang >=1.1.0
    - r-rmarkdown
    - r-rpart
    - r-rpart.plot
    - r-shiny
    - r-stringr
    - r-tibble
  run:
    - r-base
    - r-cli
    - r-dplyr >=1.1.0
    - r-dt >=0.3.0
    - r-forcats >=1.0.0
    - r-ggplot2 >=3.4.0
    - r-gridextra
    - r-magrittr
    - r-palmerpenguins
    - r-plotly
    - r-rlang >=1.1.0
    - r-rmarkdown
    - r-rpart
    - r-rpart.plot
    - r-shiny
    - r-stringr
    - r-tibble

test:
  commands:
    - $R -e "library('explore')"           # [not win]
    - "\"%R%\" -e \"library('explore')\""  # [win]

about:
  home: https://rolkra.github.io/explore/
  dev_url: https://github.com/rolkra/explore/
  license: MIT
  summary: Interactive data exploration with one line of code or use an easy to remember set of tidy functions for exploratory data analysis. Introduces three main verbs. explore() to graphically explore a variable or table, describe() to describe a variable or table and report() to create an automated report.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
