{% set version = "1.1.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-explore
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/explore_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/explore/explore_{{ version }}.tar.gz
  sha256: c35de5aa08c5552ed0ece7aff6eb225f5f9aefafd1d6a64c012447c892a1fc1a

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli
    - r-dplyr
    - r-dt >=0.3.0
    - r-forcats >=1.0.0
    - r-ggplot2 >=3.4.0
    - r-gridextra
    - r-magrittr
    - r-palmerpenguins
    - r-rlang >=1.1.0
    - r-rmarkdown
    - r-rpart
    - r-rpart.plot
    - r-shiny
    - r-stringr
    - r-tibble
  run:
    - r-base
    - r-cli
    - r-dplyr
    - r-dt >=0.3.0
    - r-forcats >=1.0.0
    - r-ggplot2 >=3.4.0
    - r-gridextra
    - r-magrittr
    - r-palmerpenguins
    - r-rlang >=1.1.0
    - r-rmarkdown
    - r-rpart
    - r-rpart.plot
    - r-shiny
    - r-stringr
    - r-tibble

test:
  commands:
    - $R -e "library('explore')"           # [not win]
    - "\"%R%\" -e \"library('explore')\""  # [win]

about:
  home: https://github.com/rolkra/explore/
  license: GPL-3.0-only
  summary: Interactive data exploration with one line of code or use an easy to remember set of tidy functions for exploratory data analysis. Introduces three main verbs. explore() to graphically explore a variable or table, describe() to describe a variable or table and report() to create an automated report.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
